# Generated by Django 3.1.1 on 2020-09-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда комфорта',
                'verbose_name_plural': 'Звезды комфорта',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_images/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда безопасности',
                'verbose_name_plural': 'Звезды безопасности',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('places', models.SmallIntegerField(default=0, verbose_name='Количество мест')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('comfortstar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parking.comfortstar', verbose_name='Звезда Комфорта')),
                ('safetystar', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parking.safetystar', verbose_name='Звезда безопасности')),
            ],
        ),
    ]
